################################################################
#  PDML (Practical Data and Markup Language) for SublimeText:  #
#  https://github.com/tajmone/Sublime-PDML                     #
################################################################

dist: trusty

git:
  depth: false

install:
  - npm install -g eclint

script:
  # ==============================================
  # EditorConfig Code Styles Validation via EClint
  # ==============================================
  # https://editorconfig.org
  # https://www.npmjs.com/package/eclint
  - bash ./validate.sh
